### ISSUE TITLE
loading thepackage 

### ISSUE THREAD

**Issue by atang35** [PM25/SimpleDarkBlue-BeamerTheme#3]
The package does not load if \usepackage{Simple} is declared in the preamble as suggested in the sample .tex file. Rather, \usepackage{SimpleDarkBlue} works.

**Comment by pm25** [comment]
Hi,
In sample.tex file, I used `\usetheme{Simple}` instead of `\usepackage{Simple}`.
https://github.com/PM25/SimpleDarkBlue-BeamerTheme/blob/caf70aa3b77b121036ef7e8ae9ac1c3c86fda6ad/sample.tex#L5

I did not find any problems compiling sample.tex.
I'm using XeTeX 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX)
Please let me know if you still experience this problem. Thanks!

**Comment by pm25** [comment]
However, I find it quite confusing with different style file names. I will rename all the files with SimpleDarkBlue at the end. 
Commit: e670180e34dc520ae09620c0fd37df79c413819f
